modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/OrderedChaos-Dev/Genesis/issues"
license="lol"

[[mods]]
	modId="genesis"
	version="${version}"
	displayName="Genesis"
	displayURL="https://www.ordered-chaos.dev/"
	logoFile="genesis.png"
	authors="solis_nova"
	description='''
	A lightweight biome mod!
	'''
[[dependencies.genesis]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.genesis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"
